services:
  mongodb:
    image: mongo
    container_name: mongo_db
    ports:
      - 27017:27
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=simon
      - MONGO_INITDB_ROOT_PASSWORD=simon
  mongo-express:
    image: mongo-express
    container_name: mongo_express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=simon
      - ME_CONFIG_MONGODB_ADMINPASSWORD=simon
      - ME_CONFIG_MONGODB_SERVER=mongodb
volumes:
  mongo: {}
